# Generated by Django 5.2.7 on 2025-10-31 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurantcuisine',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
