# Generated by Django 5.2.7 on 2025-10-31 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_restaurant_name_alter_restaurantcuisine_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantmenu',
            name='available',
        ),
    ]
