# Generated by Django 5.2.7 on 2025-11-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_restaurantmenu_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(choices=[('FILIPINO', 'Filipino'), ('JAPANESE', 'Japanese'), ('ITALIAN', 'Italian'), ('AMERICAN', 'American'), ('CHINESE', 'Chinese'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.DeleteModel(
            name='RestaurantCuisine',
        ),
    ]
