# Generated by Django 5.2.7 on 2025-10-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_projectcategory_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='projecttask',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_task_per_project'),
        ),
    ]
