# Generated by Django 5.2.7 on 2025-11-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_projecttask_unique_task_per_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('WEB', 'Web Development'), ('MOBILE', 'Mobile App'), ('DATA', 'Data Science'), ('AI', 'Artificial Intelligence'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.DeleteModel(
            name='ProjectCategory',
        ),
    ]
